package com.cn.system.dao.mapper;

import com.cn.system.dao.model.AreaProvince;
import com.cn.system.dao.model.AreaProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AreaProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=AreaProvinceSqlProvider.class, method="countByExample")
    long countByExample(AreaProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @DeleteProvider(type=AreaProvinceSqlProvider.class, method="deleteByExample")
    int deleteByExample(AreaProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Delete({
        "delete from area_province",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Insert({
        "insert into area_province (prov_name, fk_region_id)",
        "values (#{provName,jdbcType=VARCHAR}, #{fkRegionId,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @InsertProvider(type=AreaProvinceSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(AreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=AreaProvinceSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="prov_name", property="provName", jdbcType=JdbcType.VARCHAR),
        @Result(column="fk_region_id", property="fkRegionId", jdbcType=JdbcType.INTEGER)
    })
    List<AreaProvince> selectByExample(AreaProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Select({
        "select",
        "id, prov_name, fk_region_id",
        "from area_province",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="prov_name", property="provName", jdbcType=JdbcType.VARCHAR),
        @Result(column="fk_region_id", property="fkRegionId", jdbcType=JdbcType.INTEGER)
    })
    AreaProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaProvinceSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AreaProvince record, @Param("example") AreaProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaProvinceSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AreaProvince record, @Param("example") AreaProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaProvinceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AreaProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_province
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Update({
        "update area_province",
        "set prov_name = #{provName,jdbcType=VARCHAR},",
          "fk_region_id = #{fkRegionId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AreaProvince record);
}