package com.cn.system.dao.mapper;

import com.cn.system.dao.model.AreaDistrict;
import com.cn.system.dao.model.AreaDistrictExample.Criteria;
import com.cn.system.dao.model.AreaDistrictExample.Criterion;
import com.cn.system.dao.model.AreaDistrictExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class AreaDistrictSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String countByExample(AreaDistrictExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("area_district");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String deleteByExample(AreaDistrictExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("area_district");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String insertSelective(AreaDistrict record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("area_district");
        
        if (record.getFkProvId() != null) {
            sql.VALUES("fk_prov_id", "#{fkProvId,jdbcType=INTEGER}");
        }
        
        if (record.getFkCityId() != null) {
            sql.VALUES("fk_city_id", "#{fkCityId,jdbcType=INTEGER}");
        }
        
        if (record.getZipCode() != null) {
            sql.VALUES("zip_code", "#{zipCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrictName() != null) {
            sql.VALUES("district_name", "#{districtName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String selectByExample(AreaDistrictExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("fk_prov_id");
        sql.SELECT("fk_city_id");
        sql.SELECT("zip_code");
        sql.SELECT("district_name");
        sql.FROM("area_district");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AreaDistrict record = (AreaDistrict) parameter.get("record");
        AreaDistrictExample example = (AreaDistrictExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("area_district");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getFkProvId() != null) {
            sql.SET("fk_prov_id = #{record.fkProvId,jdbcType=INTEGER}");
        }
        
        if (record.getFkCityId() != null) {
            sql.SET("fk_city_id = #{record.fkCityId,jdbcType=INTEGER}");
        }
        
        if (record.getZipCode() != null) {
            sql.SET("zip_code = #{record.zipCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrictName() != null) {
            sql.SET("district_name = #{record.districtName,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("area_district");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("fk_prov_id = #{record.fkProvId,jdbcType=INTEGER}");
        sql.SET("fk_city_id = #{record.fkCityId,jdbcType=INTEGER}");
        sql.SET("zip_code = #{record.zipCode,jdbcType=VARCHAR}");
        sql.SET("district_name = #{record.districtName,jdbcType=VARCHAR}");
        
        AreaDistrictExample example = (AreaDistrictExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String updateByPrimaryKeySelective(AreaDistrict record) {
        SQL sql = new SQL();
        sql.UPDATE("area_district");
        
        if (record.getFkProvId() != null) {
            sql.SET("fk_prov_id = #{fkProvId,jdbcType=INTEGER}");
        }
        
        if (record.getFkCityId() != null) {
            sql.SET("fk_city_id = #{fkCityId,jdbcType=INTEGER}");
        }
        
        if (record.getZipCode() != null) {
            sql.SET("zip_code = #{zipCode,jdbcType=VARCHAR}");
        }
        
        if (record.getDistrictName() != null) {
            sql.SET("district_name = #{districtName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected void applyWhere(SQL sql, AreaDistrictExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}