package com.cn.system.dao.mapper;

import com.cn.system.dao.model.AreaDistrict;
import com.cn.system.dao.model.AreaDistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AreaDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=AreaDistrictSqlProvider.class, method="countByExample")
    long countByExample(AreaDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @DeleteProvider(type=AreaDistrictSqlProvider.class, method="deleteByExample")
    int deleteByExample(AreaDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Delete({
        "delete from area_district",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Insert({
        "insert into area_district (fk_prov_id, fk_city_id, ",
        "zip_code, district_name)",
        "values (#{fkProvId,jdbcType=INTEGER}, #{fkCityId,jdbcType=INTEGER}, ",
        "#{zipCode,jdbcType=VARCHAR}, #{districtName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AreaDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @InsertProvider(type=AreaDistrictSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(AreaDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=AreaDistrictSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fk_prov_id", property="fkProvId", jdbcType=JdbcType.INTEGER),
        @Result(column="fk_city_id", property="fkCityId", jdbcType=JdbcType.INTEGER),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="district_name", property="districtName", jdbcType=JdbcType.VARCHAR)
    })
    List<AreaDistrict> selectByExample(AreaDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Select({
        "select",
        "id, fk_prov_id, fk_city_id, zip_code, district_name",
        "from area_district",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="fk_prov_id", property="fkProvId", jdbcType=JdbcType.INTEGER),
        @Result(column="fk_city_id", property="fkCityId", jdbcType=JdbcType.INTEGER),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="district_name", property="districtName", jdbcType=JdbcType.VARCHAR)
    })
    AreaDistrict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaDistrictSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AreaDistrict record, @Param("example") AreaDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaDistrictSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AreaDistrict record, @Param("example") AreaDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=AreaDistrictSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AreaDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_district
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Update({
        "update area_district",
        "set fk_prov_id = #{fkProvId,jdbcType=INTEGER},",
          "fk_city_id = #{fkCityId,jdbcType=INTEGER},",
          "zip_code = #{zipCode,jdbcType=VARCHAR},",
          "district_name = #{districtName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AreaDistrict record);
}