package com.cn.system.dao.mapper;

import com.cn.system.dao.model.MenuTree;
import com.cn.system.dao.model.MenuTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MenuTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=MenuTreeSqlProvider.class, method="countByExample")
    long countByExample(MenuTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @DeleteProvider(type=MenuTreeSqlProvider.class, method="deleteByExample")
    int deleteByExample(MenuTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Delete({
        "delete from menu_tree",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Insert({
        "insert into menu_tree (name, pid, ",
        "icon, url, del)",
        "values (#{name,jdbcType=VARCHAR}, #{pid,jdbcType=BIGINT}, ",
        "#{icon,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{del,jdbcType=SMALLINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(MenuTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @InsertProvider(type=MenuTreeSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(MenuTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=MenuTreeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.BIGINT),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="del", property="del", jdbcType=JdbcType.SMALLINT)
    })
    List<MenuTree> selectByExample(MenuTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Select({
        "select",
        "id, name, pid, icon, url, del",
        "from menu_tree",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.BIGINT),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="del", property="del", jdbcType=JdbcType.SMALLINT)
    })
    MenuTree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=MenuTreeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MenuTree record, @Param("example") MenuTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=MenuTreeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MenuTree record, @Param("example") MenuTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=MenuTreeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MenuTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_tree
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Update({
        "update menu_tree",
        "set name = #{name,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=BIGINT},",
          "icon = #{icon,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "del = #{del,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MenuTree record);
}