package com.cn.system.dao.mapper;

import com.cn.system.dao.model.UserRoles;
import com.cn.system.dao.model.UserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=UserRolesSqlProvider.class, method="countByExample")
    long countByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @DeleteProvider(type=UserRolesSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @Insert({
        "insert into user_roles (rid, uid)",
        "values (#{rid,jdbcType=BIGINT}, #{uid,jdbcType=BIGINT})"
    })
    int insert(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @InsertProvider(type=UserRolesSqlProvider.class, method="insertSelective")
    int insertSelective(UserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @SelectProvider(type=UserRolesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="rid", property="rid", jdbcType=JdbcType.BIGINT),
        @Result(column="uid", property="uid", jdbcType=JdbcType.BIGINT)
    })
    List<UserRoles> selectByExample(UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=UserRolesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserRoles record, @Param("example") UserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    @UpdateProvider(type=UserRolesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserRoles record, @Param("example") UserRolesExample example);
}