package com.cn.system.dao.model;

import java.util.ArrayList;
import java.util.List;

public class AreaCityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public AreaCityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("city_name is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("city_name is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("city_name =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("city_name <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("city_name >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("city_name >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("city_name <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("city_name <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("city_name like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("city_name not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("city_name in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("city_name not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("city_name between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("city_name not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andFkProvIdIsNull() {
            addCriterion("fk_prov_id is null");
            return (Criteria) this;
        }

        public Criteria andFkProvIdIsNotNull() {
            addCriterion("fk_prov_id is not null");
            return (Criteria) this;
        }

        public Criteria andFkProvIdEqualTo(Integer value) {
            addCriterion("fk_prov_id =", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdNotEqualTo(Integer value) {
            addCriterion("fk_prov_id <>", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdGreaterThan(Integer value) {
            addCriterion("fk_prov_id >", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fk_prov_id >=", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdLessThan(Integer value) {
            addCriterion("fk_prov_id <", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdLessThanOrEqualTo(Integer value) {
            addCriterion("fk_prov_id <=", value, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdIn(List<Integer> values) {
            addCriterion("fk_prov_id in", values, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdNotIn(List<Integer> values) {
            addCriterion("fk_prov_id not in", values, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdBetween(Integer value1, Integer value2) {
            addCriterion("fk_prov_id between", value1, value2, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andFkProvIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fk_prov_id not between", value1, value2, "fkProvId");
            return (Criteria) this;
        }

        public Criteria andPinyinNameIsNull() {
            addCriterion("pinyin_name is null");
            return (Criteria) this;
        }

        public Criteria andPinyinNameIsNotNull() {
            addCriterion("pinyin_name is not null");
            return (Criteria) this;
        }

        public Criteria andPinyinNameEqualTo(String value) {
            addCriterion("pinyin_name =", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameNotEqualTo(String value) {
            addCriterion("pinyin_name <>", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameGreaterThan(String value) {
            addCriterion("pinyin_name >", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameGreaterThanOrEqualTo(String value) {
            addCriterion("pinyin_name >=", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameLessThan(String value) {
            addCriterion("pinyin_name <", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameLessThanOrEqualTo(String value) {
            addCriterion("pinyin_name <=", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameLike(String value) {
            addCriterion("pinyin_name like", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameNotLike(String value) {
            addCriterion("pinyin_name not like", value, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameIn(List<String> values) {
            addCriterion("pinyin_name in", values, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameNotIn(List<String> values) {
            addCriterion("pinyin_name not in", values, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameBetween(String value1, String value2) {
            addCriterion("pinyin_name between", value1, value2, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andPinyinNameNotBetween(String value1, String value2) {
            addCriterion("pinyin_name not between", value1, value2, "pinyinName");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinIsNull() {
            addCriterion("first_pinyin is null");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinIsNotNull() {
            addCriterion("first_pinyin is not null");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinEqualTo(String value) {
            addCriterion("first_pinyin =", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinNotEqualTo(String value) {
            addCriterion("first_pinyin <>", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinGreaterThan(String value) {
            addCriterion("first_pinyin >", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinGreaterThanOrEqualTo(String value) {
            addCriterion("first_pinyin >=", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinLessThan(String value) {
            addCriterion("first_pinyin <", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinLessThanOrEqualTo(String value) {
            addCriterion("first_pinyin <=", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinLike(String value) {
            addCriterion("first_pinyin like", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinNotLike(String value) {
            addCriterion("first_pinyin not like", value, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinIn(List<String> values) {
            addCriterion("first_pinyin in", values, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinNotIn(List<String> values) {
            addCriterion("first_pinyin not in", values, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinBetween(String value1, String value2) {
            addCriterion("first_pinyin between", value1, value2, "firstPinyin");
            return (Criteria) this;
        }

        public Criteria andFirstPinyinNotBetween(String value1, String value2) {
            addCriterion("first_pinyin not between", value1, value2, "firstPinyin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_city
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 07 12:42:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table area_city
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}