package com.cn.system.dao.model;


import com.cn.system.dao.bean.BaseRequest;

public class AreaDistrict extends BaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_district.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_district.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Integer fkProvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_district.fk_city_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Integer fkCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_district.zip_code
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_district.district_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String districtName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_district.id
     *
     * @return the value of area_district.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_district.id
     *
     * @param id the value for area_district.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_district.fk_prov_id
     *
     * @return the value of area_district.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Integer getFkProvId() {
        return fkProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_district.fk_prov_id
     *
     * @param fkProvId the value for area_district.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setFkProvId(Integer fkProvId) {
        this.fkProvId = fkProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_district.fk_city_id
     *
     * @return the value of area_district.fk_city_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Integer getFkCityId() {
        return fkCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_district.fk_city_id
     *
     * @param fkCityId the value for area_district.fk_city_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setFkCityId(Integer fkCityId) {
        this.fkCityId = fkCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_district.zip_code
     *
     * @return the value of area_district.zip_code
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_district.zip_code
     *
     * @param zipCode the value for area_district.zip_code
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_district.district_name
     *
     * @return the value of area_district.district_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_district.district_name
     *
     * @param districtName the value for area_district.district_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }
}