package com.cn.system.dao.model;


import com.cn.system.dao.bean.BaseRequest;

public class AreaCity extends BaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_city.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_city.city_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_city.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Integer fkProvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_city.pinyin_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String pinyinName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area_city.first_pinyin
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String firstPinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_city.id
     *
     * @return the value of area_city.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_city.id
     *
     * @param id the value for area_city.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_city.city_name
     *
     * @return the value of area_city.city_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_city.city_name
     *
     * @param cityName the value for area_city.city_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_city.fk_prov_id
     *
     * @return the value of area_city.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Integer getFkProvId() {
        return fkProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_city.fk_prov_id
     *
     * @param fkProvId the value for area_city.fk_prov_id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setFkProvId(Integer fkProvId) {
        this.fkProvId = fkProvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_city.pinyin_name
     *
     * @return the value of area_city.pinyin_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getPinyinName() {
        return pinyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_city.pinyin_name
     *
     * @param pinyinName the value for area_city.pinyin_name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setPinyinName(String pinyinName) {
        this.pinyinName = pinyinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area_city.first_pinyin
     *
     * @return the value of area_city.first_pinyin
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getFirstPinyin() {
        return firstPinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area_city.first_pinyin
     *
     * @param firstPinyin the value for area_city.first_pinyin
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setFirstPinyin(String firstPinyin) {
        this.firstPinyin = firstPinyin;
    }
}