package com.cn.system.dao.model;

import com.cn.system.dao.bean.BaseRequest;

import java.util.Date;

public class HtUser extends BaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.user_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.user_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.password
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.type
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.nick_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.true_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String trueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.del
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Short del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.state
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.create_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.update_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.fk_create_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Long fkCreateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.fk_update_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private Long fkUpdateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.fk_create_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String fkCreateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.fk_update_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String fkUpdateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ht_user.phone
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.user_id
     *
     * @return the value of ht_user.user_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.user_id
     *
     * @param userId the value for ht_user.user_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.user_name
     *
     * @return the value of ht_user.user_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.user_name
     *
     * @param userName the value for ht_user.user_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.password
     *
     * @return the value of ht_user.password
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.password
     *
     * @param password the value for ht_user.password
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.type
     *
     * @return the value of ht_user.type
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.type
     *
     * @param type the value for ht_user.type
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.nick_name
     *
     * @return the value of ht_user.nick_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.nick_name
     *
     * @param nickName the value for ht_user.nick_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.true_name
     *
     * @return the value of ht_user.true_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.true_name
     *
     * @param trueName the value for ht_user.true_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.del
     *
     * @return the value of ht_user.del
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.del
     *
     * @param del the value for ht_user.del
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setDel(Short del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.state
     *
     * @return the value of ht_user.state
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.state
     *
     * @param state the value for ht_user.state
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.create_time
     *
     * @return the value of ht_user.create_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.create_time
     *
     * @param createTime the value for ht_user.create_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.update_time
     *
     * @return the value of ht_user.update_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.update_time
     *
     * @param updateTime the value for ht_user.update_time
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.fk_create_id
     *
     * @return the value of ht_user.fk_create_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Long getFkCreateId() {
        return fkCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.fk_create_id
     *
     * @param fkCreateId the value for ht_user.fk_create_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setFkCreateId(Long fkCreateId) {
        this.fkCreateId = fkCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.fk_update_id
     *
     * @return the value of ht_user.fk_update_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public Long getFkUpdateId() {
        return fkUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.fk_update_id
     *
     * @param fkUpdateId the value for ht_user.fk_update_id
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setFkUpdateId(Long fkUpdateId) {
        this.fkUpdateId = fkUpdateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.fk_create_name
     *
     * @return the value of ht_user.fk_create_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getFkCreateName() {
        return fkCreateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.fk_create_name
     *
     * @param fkCreateName the value for ht_user.fk_create_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setFkCreateName(String fkCreateName) {
        this.fkCreateName = fkCreateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.fk_update_name
     *
     * @return the value of ht_user.fk_update_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getFkUpdateName() {
        return fkUpdateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.fk_update_name
     *
     * @param fkUpdateName the value for ht_user.fk_update_name
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setFkUpdateName(String fkUpdateName) {
        this.fkUpdateName = fkUpdateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ht_user.phone
     *
     * @return the value of ht_user.phone
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ht_user.phone
     *
     * @param phone the value for ht_user.phone
     *
     * @mbg.generated Wed Mar 07 12:44:12 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}