package com.cn.system.dao.model;


import com.cn.system.dao.bean.BaseRequest;

public class MenuTree extends BaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.pid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.icon
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.url
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_tree.del
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Short del;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.id
     *
     * @return the value of menu_tree.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.id
     *
     * @param id the value for menu_tree.id
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.name
     *
     * @return the value of menu_tree.name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.name
     *
     * @param name the value for menu_tree.name
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.pid
     *
     * @return the value of menu_tree.pid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.pid
     *
     * @param pid the value for menu_tree.pid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.icon
     *
     * @return the value of menu_tree.icon
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.icon
     *
     * @param icon the value for menu_tree.icon
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.url
     *
     * @return the value of menu_tree.url
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.url
     *
     * @param url the value for menu_tree.url
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_tree.del
     *
     * @return the value of menu_tree.del
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Short getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_tree.del
     *
     * @param del the value for menu_tree.del
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setDel(Short del) {
        this.del = del;
    }
}