package com.cn.system.dao.model;


import com.cn.system.dao.bean.BaseRequest;

public class UserRoles extends BaseRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.rid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.uid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    private Long uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.rid
     *
     * @return the value of user_roles.rid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.rid
     *
     * @param rid the value for user_roles.rid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.uid
     *
     * @return the value of user_roles.uid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.uid
     *
     * @param uid the value for user_roles.uid
     *
     * @mbg.generated Wed Mar 07 12:42:47 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }
}